name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Podman using Homebrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> "$GITHUB_PATH"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install podman
      - name: Check Podman version
        run: podman version
      - name: Run Podman hello world
        run: podman run quay.io/podman/hello
      - name: Build a container image
        run: podman build . --tag myapp
      - name: Run a container
        run: |
          ID=$(podman run -dt -p3000:3000 myapp)
          curl http://localhost:3000/
          podman kill ${ID}
      - name: Check podman-machine info
        run: podman machine ls
